feat: Add custom authentication doc.
npm/npmo-docs pull request #48
Opened 2017-03-31 19:51 UTC by mahikhond

Details:
- Added custom authentication documentation for Stash and Gitlab.

2017-04-03 18:07 UTC, bcoe requested changes
this is sounding great 👍 I'm glad to have these plugins documented.

2017-04-03 18:07 UTC, bcoe commented on up-and-running/auth/custom.md
> +If authentication system use in your organization is not listed in [npme's supported authentication methods](/up-and-running/auth/#authentication) you can use custom authentication, we have provided
`If authentication system use in your organization` -> `If your authentication system is not listed in`

`you can use custom authentication, we have provided following two custom authentication plugins:` -> `you may be able to an external open-source plugin (or write your own)`. Here are some of the OSS plugins that exist:

2017-04-03 18:07 UTC, bcoe commented on up-and-running/auth/custom.md
> + * npme-auth-atlassian-stash
let's make these links to the repos.

2017-04-03 18:07 UTC, bcoe commented on up-and-running/auth/custom.md
> +You can also opt to write your own `custom auth-plugin` for npm Enterprise.
maybe add, `using one of the open-source plugins listed above as a starting point`.

2017-04-03 19:42 UTC, mahikhond commented
@bcoe Updated requested changes

2017-04-05 17:32 UTC, bcoe commented on up-and-running/auth/custom.md
> +If your authentication system is not listed in [npme's supported authentication methods](/up-and-running/auth/#authentication) you may be able to use an external open-source plugin (or write your own
`Here are some of the SSO plugins that exist` -> `Here are some of the existing third-party plugins that exist`

2017-04-12 06:00 UTC, bcoe approved these changes

2017-04-12 06:00 UTC, bcoe commented
👍 thanks for the contribution.

2017-04-12 06:01 UTC, merged