feat: Added FAQ entry for updating npm Enterprise license
npm/npmo-docs pull request #54
Opened 2017-04-13 20:47 UTC by mahikhond

2017-04-17 18:43 UTC, bcoe requested changes
sounding good 👍 just a couple updates for you.

2017-04-17 18:43 UTC, bcoe commented on troubleshooting/faq.md
> +## How do I upgrade npm Enterprise license?
Let's change this to:

"How do I update my npm Enterprise license?"

And switch `upgrade` to update elsewhere.

2017-04-17 18:43 UTC, bcoe commented on troubleshooting/faq.md
> +You can upgrade npme license by following below steps:
"by following the steps below"

2017-04-17 18:43 UTC, bcoe commented on troubleshooting/faq.md
> +You can get license key by purchasing npm Enterprise license from [here](https://www.npmjs.com/enterprise/license)
I like that you direct people to the license registration page 👍

2017-05-10 18:56 UTC, arobson requested changes

2017-05-10 18:56 UTC, arobson commented on troubleshooting/faq.md
> +You can get license key by purchasing npm Enterprise license from [here](https://www.npmjs.com/enterprise/license)
Minor change in wording/grammar: "You can get a license key by purchasing an npm Enterprise license on our [license page](https://www.npmjs.com/enterprise/license)."

2017-05-10 19:16 UTC, arobson approved these changes

2017-05-25 15:03 UTC, merged